# Generated by Django 2.2.6 on 2019-10-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('is_lawyer', models.BooleanField(default=False)),
                ('last_date', models.DateField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_bookings', models.IntegerField()),
                ('total_bookings', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('past', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=100)),
                ('empower', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('lawyer_id', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Day')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Location')),
            ],
        ),
    ]
