# Generated by Django 2.2.7 on 2019-11-26 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Denumire locatie')),
                ('details', models.CharField(max_length=100, verbose_name='Detalii locatie')),
            ],
            options={
                'verbose_name': 'Locatie',
                'verbose_name_plural': 'Locatii',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Articol')),
                ('details', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalii')),
                ('address', models.CharField(max_length=200, verbose_name='Adresa')),
                ('is_lawyer', models.BooleanField(default=False, verbose_name='Este pentru avocati')),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='Ultima zi deblocata')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Location', verbose_name='Locatie')),
            ],
            options={
                'verbose_name': 'Articol',
                'verbose_name_plural': 'Articole',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('max_bookings', models.IntegerField(verbose_name='Numar maxim de programari pe zi')),
                ('total_bookings', models.IntegerField(blank=True, null=True, verbose_name='Total programari')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Event', verbose_name='Articol')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Location', verbose_name='Locatie')),
            ],
            options={
                'verbose_name': 'Zi deblocata',
                'verbose_name_plural': 'Zile deblocate',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresa de E-mail')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creat la data de')),
                ('past', models.BooleanField(default=False, verbose_name='Data depasita')),
                ('date', models.DateField(verbose_name='Data programare')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nume')),
                ('last_name', models.CharField(max_length=100, verbose_name='Prenume')),
                ('birthday', models.DateField(verbose_name='Data nasterii')),
                ('country', models.CharField(max_length=100, verbose_name='Tara')),
                ('city', models.CharField(max_length=100, verbose_name='Oras')),
                ('passport', models.CharField(max_length=100, verbose_name='Nume pasaport')),
                ('is_lawyer', models.BooleanField(default=False, verbose_name='Este avocat')),
                ('empower', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png', 'jpeg'])], verbose_name='Imputernicire avocatiala')),
                ('lawyer_id', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png', 'jpeg'])], verbose_name='Legitimatie avocat')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Event', verbose_name='Articol')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Location', verbose_name='Locatie')),
            ],
            options={
                'verbose_name': 'Programare',
                'verbose_name_plural': 'Programari',
            },
        ),
    ]
