# Generated by Django 2.2.6 on 2019-10-08 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_is_lawyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Programare', 'verbose_name_plural': 'Programari'},
        ),
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'Zi deblocata', 'verbose_name_plural': 'Zile deblocate'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Articol', 'verbose_name_plural': 'Articole'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Locatie', 'verbose_name_plural': 'Locatii'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='birthday',
            field=models.DateField(verbose_name='Data nasterii'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Oras'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Tara'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creat la data de'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Data programare'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresa de E-mail'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='empower',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png', 'jpeg'])], verbose_name='Imputernicire avocatiala'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_lawyer',
            field=models.BooleanField(default=False, verbose_name='Este avocat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Prenume'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='lawyer_id',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png', 'jpeg'])], verbose_name='Legitimatie avocat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passport',
            field=models.CharField(max_length=100, verbose_name='Nume pasaport'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='past',
            field=models.BooleanField(default=False, verbose_name='Data depasita'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='day',
            name='max_bookings',
            field=models.IntegerField(verbose_name='Numar maxim de programari pe zi'),
        ),
        migrations.AlterField(
            model_name='day',
            name='total_bookings',
            field=models.IntegerField(verbose_name='Total programari'),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalii'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_lawyer',
            field=models.BooleanField(default=False, verbose_name='Este pentru avocati'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ultima zi deblocata'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Articol'),
        ),
        migrations.AlterField(
            model_name='location',
            name='details',
            field=models.CharField(max_length=100, verbose_name='Detalii locatie'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Denumire locatie'),
        ),
    ]
