# Generated by Django 2.2.7 on 2019-11-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20191009_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Event', verbose_name='Articol'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Location', verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='day',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Event', verbose_name='Articol'),
        ),
        migrations.AlterField(
            model_name='day',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Location', verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='day',
            name='total_bookings',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total programari'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Location', verbose_name='Locatie'),
        ),
    ]
